### ISSUE TITLE
Service stops working after some hours without any error messages

### ISSUE THREAD

**Issue by kameceres** [zapty/forever-service#100]
Dear,
I installed nodejs server as a service, and the service works perfectly each time I do start or restart.
Nodejs server is using 'mysql-events' to monitor changes on database, and 'mysql' to query needed data before emitting.

After some hours working, it does not emit any more. I have checked log files in /var/log but could not find any error messages.

'mysql-events' uses bin log, and my server also have master-master database configured that is also using the bin log.

Do you have any ideas about why it stops working like this?

Regards.

**Comment by arvind-agarwal** [comment]
The scope of forever-service is limited to just to wrap services around a startup script. So if services are starting it is working as expected. There could be several reasons why a process could stop working. I guess you have to debug your program and see why it could be happening.
