### ISSUE TITLE
pass --flag to scriptOptions param

### ISSUE THREAD

**Issue by ASafaeirad** [zapty/forever-service#101]
I want to pass flag param as scriptOptions to my service
but I get

```error: unknown option `--flag`.```

how can I do it?

**Comment by arvind-agarwal** [comment]
Please provide the full command you have used for provisioning the service.

**Comment by frontendmonster** [comment]
```forever-service install server --script dist/index.js --scriptOptions '--prod'```
will result
```error: unknown option `--prod`.```

but it worked by adding extra space before the param as below:
```forever-service install server --script dist/index.js --scriptOptions ' --prod'```
