### ISSUE TITLE
Cant start service Raspbian

### ISSUE THREAD

**Issue by Snorlock** [zapty/forever-service#11]
Hi i just installed my service 

sudo forever-service install serialReader --script serialReader.js -f " -watchDirectory /home/pi/Code/arduino-plant-reader -w"

It worked, but when i sudo service serialReader start. It says starting serialReader and goes back to the commandline. But nothing is running in sudo forever list and when i check status of the service, it says its not running. Somewhere I can debug this?

**Comment by arvind-agarwal** [comment]
Best way to debug would be look at /etc/init.d/serialReader file and extract forever start command from the start function and run it directly as sudo, if you are able to make it work typically it should work with the service also.

**Comment by Snorlock** [comment]
Sweet, il check it out when i get home

**Comment by Snorlock** [comment]
Thanks, worked now
