### ISSUE TITLE
/usr/bin/env: node: No such file or directory

### ISSUE THREAD

**Issue by robertosanval** [zapty/forever-service#12]
Hello,

I installed it on CentOS 6.4 64-bit, everything it's OK.

This is my command:
```
forever-service install -s /var/node/myapp.js -p /usr/local/bin/ myapp
```
But when I do "sudo service myapp start" I get this error:
```
/usr/bin/env: node: No such file or directory
Starting myapp
/usr/bin/env: node: No such file or directory
```
Thanks

**Comment by arvind-agarwal** [comment]
The issues seems to be related to node setup, please could be similar to 

http://stackoverflow.com/questions/20061529/sublime-text-coffeescript-build-system-env-node-no-such-file-or-directory and see if that helps.

Basically the error is coming when in init.d the forever command is launched and it is unable to find the node executable.

**Comment by robertosanval** [comment]
Thanks! It solved my problem!

**Comment by aimensasi** [comment]
@robertosanval can you share the way you solved it?

**Comment by robertosanval** [comment]
@aimensasi Just creating the symlink https://stackoverflow.com/a/20077620

**Comment by aimensasi** [comment]
Thanks a lot
