### ISSUE TITLE
start: Job failed to start on ubuntu 14.04 tls

### ISSUE THREAD

**Issue by vkhazin** [zapty/forever-service#15]
1. sudo mkdir /var/www/static-content and then cd into the new directory
2. sudo apt-get install forever-service
3. sudo forever-service install static-content --script index.js
4. sudo start static-content
5. error: start: Job failed to start

**Comment by arvind-agarwal** [comment]
Have you installed forever?

**Comment by vkhazin** [comment]
Let me try - thanks for fast response!

**Comment by arvind-agarwal** [comment]
@vkhazin Did it work for you? If yes, please close the issue.

**Comment by VKhazinGladiator** [comment]
Fixed: by installing 'forever' package using npm:
sudo npm install forever -g.
My mistake was to assume that 'forever-service' would install 'forever' package as a dependency.

**Comment by vkhazin** [comment]
I am having a trouble to 'close' the issue - the only way I could find on
github to close an issue is to commit something.
Any suggestions how do I do that?


On Thu, Jan 22, 2015 at 4:05 AM, arvind-agarwal <notifications@github.com>
wrote:

> @vkhazin <https://github.com/vkhazin> Did it work for you? If yes, please
> close the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zapty/forever-service/issues/15#issuecomment-70990389>
> .
>



-- 
Sincerely yours,
Vlad Khazin
Email: vlad.khazin@icssolutions.ca
Skype: vladimir.khazin
Cell: 416-802-2771
Fax: 866-425-2660
http://www.linkedin.com/in/vkhazin
