### ISSUE TITLE
User dir not set

### ISSUE THREAD

**Issue by vmatekole** [zapty/forever-service#17]
When running a nodejs service via forerver-service, the following application - https://github.com/bitpay/insight-api/search?utf8=%E2%9C%93&q=getUserHome%28%29 attempts to retrieve the home dir of the user, resulting in 'undefined' and thus related database files are saved in working dir, under a dir 'undefined'.

**Comment by arvind-agarwal** [comment]
Please look at #9 (Support for HOME environment variable)

**Comment by arvind-agarwal** [comment]
Basically you can use -e parameter to specify environment variables.

**Comment by arvind-agarwal** [comment]
@vmatekole is your problem resolved? BTW there is a new build 0.4.4, which fixes ubuntu specific env variable issue.

**Comment by vmatekole** [comment]
@arvind-agarwal  issue is solved. Danke!
