### ISSUE TITLE
forever: command not found on start

### ISSUE THREAD

**Issue by aronduby** [zapty/forever-service#2]
Attempting to use this tool but it keeps saying that the forever command is not found on line 51 and 63 whenever I attempt to start the service. Both forever and forever-service were installed globally as root.  Here's the full output:

```
[root@server /etc/init.d]$ forever-service install -s /web/grpl/node/server.js grpl
forever-service version 0.2.3

Platform - CentOS release 6.5 (Final)

grpl provisioned successfully

Commands to interact with service grpl
Start   - "sudo service grpl start"
Stop    - "sudo service grpl stop"
Status  - "sudo service grpl status"
Restart - "sudo service grpl restart"
[root@server /etc/init.d]$ service grpl start
/etc/init.d/grpl: line 51: forever: command not found
Starting grpl
/etc/init.d/grpl: line 63: forever: command not found
```

After my first attempt not working I removed both forever and forever-script and re-installed them (again as root) since my install of forever was getting a bit old, but that made no noticeable difference.

**Comment by buno047** [comment]
Thank you Arvind. For CentOS, I had needed to find "whereis node" Then simply create a symlink of that file to /usr/bin/node and then forever-service works fine.
