### ISSUE TITLE
centos : This platform is not yet supported by forever-service

### ISSUE THREAD

**Issue by nvcken** [zapty/forever-service#23]
My platform is 
cat /etc/*release
CentOS release 5.10 (Final)

**Comment by arvind-agarwal** [comment]
Can you paste contents of /etc/system-release file

**Comment by nvcken** [comment]
It has not /etc/system-release file

**Comment by arvind-agarwal** [comment]
so which release file it has in /etc/ for which you have put the content?

**Comment by nvcken** [comment]
/etc/redhat-release

**Comment by nvcken** [comment]
should I create system-release which copied of redhat-release

**Comment by arvind-agarwal** [comment]
Oh ok. A quick word around would be to copy redhat-release file to /etc/system-release file and it should work. Looks like older release of CentOS never had /etc/system-release file on which forever-service is relying to check the OS.
