### ISSUE TITLE
which version forever, nodemon required

### ISSUE THREAD

**Issue by nvcken** [zapty/forever-service#24]
I has try created script success with latest version of forever, nodemon .
But when I try on other system which older forever , nodemon package, cmd service start ok but I see log of forever process , It 's not work properly, seem error of nodemon or forever cmd.
Then I try update latest version of forever, nodemon .
Result service start ok, app work properly

Should has information about version required of forever, nodemon of which forever-service release  ? 
I think that is important because forever, nodemon may update or change their cli in future then error may occurs with forever-service

**Comment by arvind-agarwal** [comment]
Unless otherwise stated, I would always go with latest versions of all the dependencies.
