### ISSUE TITLE
service not start at reboot

### ISSUE THREAD

**Issue by strauss69400** [zapty/forever-service#28]
hi,

i installed forever-service in order to launch maildev at start.

i added maildev at service.
after i launched "service maildev start".
it works perfectly but when restart the system, the service is not launched.

I have to start this command every reboot :"service maildev start".

maybe i forget to execute a command.

thank you
PS: sorry for my english

**Comment by arvind-agarwal** [comment]
Please look at #21 #2

**Comment by strauss69400** [comment]
impossible to do to work forever-service at start.
I tried everything, I do not see how? .is Can you help me?

**Comment by arvind-agarwal** [comment]
Please describe steps you have done?

Also try running the forever-service command with -e "PATH=/usr/local/bin:\$PATH" parameter. and check.

**Comment by strauss69400** [comment]
yes i try this command : 
forever-service install maildev -s /usr/local/bin/maildev -e "PATH=/usr/local/bin:\$PATH".

it works.thank you very much
