### ISSUE TITLE
Doesn't work in Ubuntu 15.04

### ISSUE THREAD

**Issue by anissen** [zapty/forever-service#32]
In Ubuntu 15.04, [upstart is replaced with systemd](https://wiki.ubuntu.com/SystemdForUpstartUsers#System_Init_Daemon) which causes `forever-service` to fail.

**Comment by arvind-agarwal** [comment]
Ok, will have to check it, do the traditional sysvinit script still work in ubuntu 15.04?

**Comment by anissen** [comment]
Not according to [this article](http://www.techrepublic.com/article/ubuntu-15-04-minor-improvements-major-controversy/):
> This is a change that will have old-school admins pulling out their graying hair by the handfuls. You see, systemd is replacing the aging UNIX sysvinit startup system (which had already been replaced in Ubuntu by a system called upstart).

**Comment by mkozjak** [comment]
+1

**Comment by sukima** [comment]
Sorry for being the curmudgeon here. There hasn't been any movement on this issue since commit 6b18e7dd41a30d4c8fd30697982359bb28fbc416 on Jul 9th. Considering Ubuntu 15.x is pretty much here to stay what are the blockers?

**Comment by arvind-agarwal** [comment]
@sukima sorry for delay on this, i have been tied up with some work related prfioritize, most probably will work on this next month. For this I will be creating a daemon for systemd, so hopefully more OS flavours can be supported in future.

**Comment by dominikwilkowski** [comment]
16.04 is out and well. systemd support seems important now :)

**Comment by tony1016** [comment]
update expected!!

**Comment by arvind-agarwal** [comment]
@tony1016 there is a pull request which i have to merge, which will take few more days that will support latest ubuntu as well.

**Comment by afturner** [comment]
Thanks!
