### ISSUE TITLE
service installs but does not start automatically on reboot

### ISSUE THREAD

**Issue by rawmean** [zapty/forever-service#34]
I am able to install the service successfully, but upon reboot, the service does not start automatically.
I can run the service manually after reboot with no problem.

[update] Looking at the logs, I can see that upon reboot, it attempted to start the script but it got stuck and failed.

```
pi@raspberrypi ~/homebridge $ sudo forever-service install myHomeBridge
forever-service version 0.5.3

Platform - Raspbian GNU/Linux 7 (wheezy)
update-rc.d: using dependency based boot sequencing
myHomeBridge provisioned successfully
```

Here are the versions:
```
pi@raspberrypi ~ $ forever --version
v0.15.1
pi@raspberrypi ~ $ forever-service --version
forever-service version 0.5.3

0.5.3
```

**Comment by arvind-agarwal** [comment]
Please look at #21

**Comment by arvind-agarwal** [comment]
@rawmean can you confirm if #21 solves your issue?

**Comment by rawmean** [comment]
Thanks for the followup.  I haven’t had a chance to try it.  Planning to try this weekend. Will report back.

**Comment by rawmean** [comment]
It works perfectly now.  Thanks much!
