### ISSUE TITLE
start: Unknown job:

### ISSUE THREAD

**Issue by filipvh** [zapty/forever-service#37]
After successfully ceating a Service on Ubuntu 14.04.3 LTS, 

forever-service version 0.5.4

Platform - Ubuntu 14.04.3 LTS
runuserpath not found
grotteke provisioned successfully

Commands to interact with service grotteke
Start   - "sudo start grotteke"
Stop    - "sudo stop grotteke"
Status  - "sudo status grotteke"
Restart - "sudo restart grotteke"

I get:

>sudo start grotteke
start: Unknown job: grotteke

**Comment by arvind-agarwal** [comment]
Please share contents of /etc/init/grotteke.conf file.

**Comment by filipvh** [comment]
I think I found what makes it break :)
**Original command** : sudo forever-service install grotteke -s /home/filip/beta/Het\ Grotteke/bin/www
**New command** : sudo forever-service install grotteke -s /home/filip/beta/t/bin/www
The space in "Het Grotteke" (or Het\ Grotteke) makes the difference. 
I know spaces in file-trees are evil to some, but evil happens :p
