### ISSUE TITLE
Starting service for python script generates 2 different processes

### ISSUE THREAD

**Issue by pedroetb** [zapty/forever-service#39]
When starting a service installed to run a python script, it works properly, but then it creates 2 separate processes.

I don't know if this is the normal behaviour, but stopping the service only stop one of the two processes, so it keeps alive all the time.

Is this a bug? Any workaround?

Thanks!

**Comment by arvind-agarwal** [comment]
forever-service uses forever internally to launch the process. So basically there is a forever monitor process and actual script process. So one nodejs process and one python in this case. If you are seeing two python processes it is most likely that your script is invoking more processes, and forever-service will only try to stop the main processes and not child processes of those. (In most cases). So i would recommend checking your script.

**Comment by pedroetb** [comment]
Yes, I was checking it and I think the same, may be a child process of the python script.

So the issue is resolved now (that was fast!). Thanks!
