### ISSUE TITLE
RHEL 6 issue

### ISSUE THREAD

**Issue by buno047** [zapty/forever-service#41]
I was able to create a new install "app"by forever-service. However, when I "service app start" it doesnt work and shows:
/usr/bin/env: node: No such file or directory
Starting opiq
/usr/bin/env: node: No such file or directory

any solution? Thank you very much.

**Comment by arvind-agarwal** [comment]
Have you looked at #2 (In the bottom of the issue)

**Comment by buno047** [comment]
Thank you Arvind. For CentOS, I had needed to find "whereis node" Then simply create a symlink of that file to /usr/bin/node and then forever-service works fine.
