### ISSUE TITLE
Doesn't work in Ubuntu 15.10

### ISSUE THREAD

**Issue by mukarahan** [zapty/forever-service#49]
here the output of sudo forever-service install test

forever-service version 0.5.4

Platform - Ubuntu 15.10
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
Could not provision service
Could not add service test
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused

**Comment by arvind-agarwal** [comment]
@mukarahan currently Ubuntu 15.10 is not supported since they switched from upstart to systemd, systemd support for forever-service is in development.
