### ISSUE TITLE
No support for elementaryOS Freya

### ISSUE THREAD

**Issue by WoodyWoodsta** [zapty/forever-service#51]
Trying forever-service on elementaryOS Freya returns an error about the platform not being supported, however eOS is derived fairly closely from Ubuntu 14.04 (I think?). Any reason why it is not supported here?

**Comment by arvind-agarwal** [comment]
@WoodyWoodsta reason is just testing. If you are willing to test and send me pull request similar to #33, i can add that as supported OS.

**Comment by WoodyWoodsta** [comment]
Sure, I'll give it a go :+1:
