### ISSUE TITLE
log rotation is always daily

### ISSUE THREAD

**Issue by ericberdahl** [zapty/forever-service#54]
There exists a bug in the logrotate templates for both upstart and sysvinit in which the "logrotateFrequency" variable in the template is misspelled "logroateFrequency". The net result of this error is that the log rotation frequency is always specified as daily (defaulted from the template itself), regardless of the value specified by the user (via the --logrotateFrequency command line option).

**Comment by arvind-agarwal** [comment]
@ericberdahl thanks for pointing this out. I have fixed it can you upgrade to 0.5.6 and confirm if this works now.

**Comment by ericberdahl** [comment]
@arvind-agarwal Confirmed. Upgraded forever-service to 0.5.6 and ran an install. logrotate configuration file now shows the rotation frequency specified by the argument to forever-service. Thanks!
