### ISSUE TITLE
Don't start with system startup on Raspbian

### ISSUE THREAD

**Issue by thekip** [zapty/forever-service#57]
Service succesfully start by:

```bash
sudo service smarthome start
```

But don't start when system reboot. I checked up rc.d folders and all was correct. (there is links in rc2-rc5 to script).

Then I try to restart system, and didn't see nothing running in htop. 

Logs for this service is empty. Syslog is empty to. 

Why it don't start at startup? How to find a reason? May be need to change startup order for service? 

My system is: 
Raspberry PI, arm v7, Raspbian Jessie.
NodeJS script depends on SerialPort (usb2serial dongle), and open 80 port. 
Pi connected to the LAN via WIFI usb adapter.

**Comment by arvind-agarwal** [comment]
Please look at #21

**Comment by thekip** [comment]
Yes, it works. Thanks. You should add it to FAQ or readme
