### ISSUE TITLE
Manually restart service provisioned through forever-service?

### ISSUE THREAD

**Issue by dmarkhas** [zapty/forever-service#59]
Perhaps I am missing something, but how can I manually start or stop a service that was provisioned with forever-service, after it has been installed?

I am running on Ubuntu 14.04, and after installing the service (forever-service install myservice), if I don't use the --start option, I am unable to start it as it doesn't get added as a service on Ubuntu (so service myservice start fails saying myservice is unrecognized), and I also cannot manually start it with forever (also says that it is unrecognized).

Can someone point me in the right direction?

**Comment by bzkdjc** [comment]
On my Ubuntu 14.04, I simply use: 
```bash
sudo start <forever-service-name>   # to start the service 
sudo stop <forever-service-name>    # to stop the service 
```
whenever I want to start or stop any _forever-service_ service.

**Comment by dmarkhas** [comment]
Thanks, that helps. Looks like restart doesn't work if the service is stopped, but that's sufficient for me.
