### ISSUE TITLE
Running with a command and no entry point

### ISSUE THREAD

**Issue by pjnovas** [zapty/forever-service#67]
Hey there, I have the following start with forever (which works):

```bash
sudo forever start -c "npm run start" ./
```

Can I run that with forever-service?, how do I send the path?

I have tried with no luck:
```bash
sudo forever-service install servicename -f " -c npm run start" --start
```
Which gives the error:
```bash
forever-service version 0.5.4

Platform - Ubuntu 14.04.1 LTS
runuserpath not found
app.js not found
```

**Comment by arvind-agarwal** [comment]
May be you can try,

``sudo forever-service install servicename -f " -c npm run start" -s ./``

**Comment by pjnovas** [comment]
thanks!

**Comment by light9** [comment]
You need to add single quotes inside forever arguments: 'npm run start'. Without them I cant get it works.
So my solution is: `sudo forever-service install servicename -f " -c 'npm run start'" -s ./`.

**Comment by krestaino** [comment]
@light9 That is working for me to install the service and start it, but when I stop the service, the app is still running. Any idea why that might be?
