### ISSUE TITLE
Command line options to your app.js

### ISSUE THREAD

**Issue by morrisonbrett** [zapty/forever-service#7]
Is there a way to pass command line options into the app?

e.g. $ sudo forever-service install myapp -s "myapp.js -myarg foo"

**Comment by ravi-nextbit** [comment]
It seems that specifying parameters with a leading dash are interpreted as option to forever-service. Trying to install a service with these options fails:

```
sudo forever-service install myservice -s index.js -r nodejs -o "-c /confdir"
=> error: unknown option `-c'
```
