### ISSUE TITLE
"Invalid env variable" error when environment variable contains "="

### ISSUE THREAD

**Issue by nemecec** [zapty/forever-service#78]
I have an environment variable:
`MONGO_URI="mongodb://user:password@host1:15145,host2:15145/db-name?ssl=true"`

This should be perfectly legal environment variable. However, forever service script assumes that there are no "=" characters in the environment variable value and reports an error.

Fix: When splitting the environment variable definition to get variable name, just use the first "=" character.

**Comment by paivaric** [comment]
same issue

**Comment by mfa777** [comment]
not yet solved.

**Comment by arvind-agarwal** [comment]
can someone send me a pull request for this fix?

**Comment by jackSnaps** [comment]
Also having this issue

**Comment by zedar187** [comment]
@arvind-agarwal: I've made a pull request (my first one on github \o/) with a quick fix. The code searches for the first apearrance of an = symbol and uses the rest as a whole env variable value.

**Comment by arvind-agarwal** [comment]
Fixed in 0.5.10
