### ISSUE TITLE
Support for HOME environment variable

### ISSUE THREAD

**Issue by morrisonbrett** [zapty/forever-service#9]
I have a requirement to run a node app as a particular user.  I had to manually modify your generated .conf file and add the line:

env HOME=/home/myusername

to get my node app to run in the proper context.

Would be great if forever-service supported adding this line.

**Comment by arvind-agarwal** [comment]
@morrisonbrett  with the new pull request from @AshyIsMe merged in 0.4.3, I am closing this request now.

**Comment by morrisonbrett** [comment]
Thanks guys!
